name: CI
 
on:
  push:
    branches: [ master ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
     -   
        name: Checkout
        uses: actions/checkout@v2
     -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
     - 
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
     - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

     - 
        name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags:  amrmetwallydocker/inteface-generator:latest
          context: .
          file: ./Dockerfile
     -
         name: Image Digest
         run: echo ${{ steps.docker_build.outputs.digest }}
