name: CI
 
on:
  push:
    branches: [ master ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
     - 
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
     - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

     - 
        name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags:  inteface-generator:latest 
          build-args: |
            arg1=value1
            arg2=value2
     -
         name: Image Digest
         run: echo ${{ steps.docker_build.outputs.digest }}
