name: CI
 
on:
  push:
    branches: [ master ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel  
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Build the Docker Image and Push it to Dockerhub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags:  inteface-generator:latest  
      -
         name: Image Digest
         run: echo ${{ steps.docker_build.outputs.digest }}
